summary: apache2 k8s test

execute: |

  # Cilium (CNI) is not yet supported on s390x and ppc64le
  # so we'll skip the k8s tests on those architectures for now
  # ---
  # TODO: Remove this check once Cilium supports s390x and ppc64le
  if [ "$(uname -m)" = "s390x" ] || [ "$(uname -m)" = "ppc64le" ]; then
    echo "Skipping k8s tests on $(uname -m) architecture"
    exit 0
  fi

  k8s kubectl create configmap apache2-config --from-file=apache2=apache2.conf --from-file=apache2-site=index.html
  k8s kubectl apply -f deployment.yaml

  timeout 30 bash -c 'until curl -sSf http://127.0.0.1:30080 >/dev/null; do sleep 1; done'

  curl -sSf http://127.0.0.1:30080 | grep "It works!"